### ISSUE TITLE
MIDI_TIME_CODE Constant

### ISSUE THREAD

**Issue by iliTheFallen** [OFAI/python-midi#1]
Hi,

There is no constant called "MIDI_TIME_CODE" defined in MidiOutFile.py on line 185. What is it? Where should it have been defined?

Thank you.

**Comment by f0k** [comment]
Thank you for the report! Looking at the code, the constants seem to come from `from constants import *`, and `constants.py` defines `MTC`: https://github.com/OFAI/python-midi/blob/master/midi_backend/constants.py#L133
Looking further, `MTC` is used in two other places, but `MIDI_TIME_CODE` isn't. So the correct fix would be to replace `MIDI_TIME_CODE` with `MTC` in `MidiOutFile.py`. I'll send a PR, but I don't know if @mgrachten is still maintaining this.

**Comment by mgrachten** [comment]
Many thanks @iliTheFallen for reporting, and @f0k for fixing the bug! FYI: The code in the `midi_backend` folder was taken from a now defunct [website](http://www.mxm.dk/products/public/pythonmidi) that stated the code could be used freely, but without including any explicit license and copyright statement.

I just checked and noticed that the original author has recently put his [code on github](https://github.com/maxmcorp/mxm.midi) (including the bug fixed here), but states that the code is unmaintained, probably because it is superseded by [a python 3 version](https://github.com/maxmcorp/mxm.midifile).

The bug also persists in the python 3 version. If any of you feels like creating a pull request for MXM's repositories feel free, otherwise I will do it.

**Comment by maxmcorp** [comment]
@mgrachten I am the original Author. You are free to use the code as you like.

I won't be using it in python 2 anymore, but I will maintain the Python 3 version. Which is basically a complete rewrite.

**Comment by mgrachten** [comment]
> You are free to use the code as you like.

Thank you @maxmcorp, I'm glad to hear that! My redistribution of your code on github was to facilitate the distribution of our own code which depends on your package.
